[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Instructs Netlify to use the correct Node version
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
