const { Client } = require("pg");

const client = new Client({
  connectionString: "postgresql://postgres.zfytdnpgszqfasfenqtt:Regor%408806329362@aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres",
});

const mockProperties = [
  {
    id: "e51241df-a567-488f-9e6e-214152db4901",
    title: "Luxury Portuguese Villa in Assagao",
    location: "Assagao, North Goa",
    price: "₹ 14.50 Cr",
    image: "/images/villa-1.webp",
    bedrooms: 5,
    bathrooms: 5,
    area: "4800 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "luxury-portuguese-villa-assagao",
  },
  {
    id: "f42352ef-b678-499f-af7f-325263ec5012",
    title: "Sunset View Penthouse in Anjuna",
    location: "Anjuna, North Goa",
    price: "₹ 5.25 Cr",
    image: "/images/villa-2.webp",
    bedrooms: 3,
    bathrooms: 3,
    area: "2100 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "sunset-view-penthouse-anjuna",
  },
  {
    id: "a1111111-1234-4567-89ab-cdef01234567",
    title: "Beachfront Bungalow in Morjim",
    location: "Morjim, North Goa",
    price: "₹ 18.00 Cr",
    image: "/images/villa-3.webp",
    bedrooms: 4,
    bathrooms: 4,
    area: "3500 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "beachfront-bungalow-morjim",
  },
  {
    id: "b2222222-2345-5678-9abc-def012345678",
    title: "Modernist Forest Villa in Siolim",
    location: "Siolim, North Goa",
    price: "₹ 8.75 Cr",
    image: "/images/villa-4.webp",
    bedrooms: 4,
    bathrooms: 4,
    area: "3800 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "modernist-forest-villa-siolim",
  },
  {
    id: "c3333333-3456-6789-abcd-ef0123456789",
    title: "Heritage Mansion in Panaji",
    location: "Panaji, Central Goa",
    price: "₹ 22.00 Cr",
    image: "/images/villa-1.webp",
    bedrooms: 6,
    bathrooms: 6,
    area: "6500 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "heritage-mansion-panaji",
  },
  {
    id: "d4444444-4567-7890-bcde-f0123456789a",
    title: "Clifftop Estate in Vagator",
    location: "Vagator, North Goa",
    price: "₹ 16.20 Cr",
    image: "/images/villa-2.webp",
    bedrooms: 5,
    bathrooms: 6,
    area: "5200 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "clifftop-estate-vagator",
  },
  {
    id: "e5555555-5678-8901-cdef-0123456789ab",
    title: "Luxury Condo near Miramar Beach",
    location: "Miramar, Panaji, Goa",
    price: "₹ 1.20 L / mo",
    image: "/images/villa-3.webp",
    bedrooms: 2,
    bathrooms: 2,
    area: "1400 sq.ft.",
    listingType: "rent",
    verified: true,
    slug: "luxury-condo-miramar-beach",
  },
  {
    id: "f6666666-6789-9012-def0-123456789abc",
    title: "Riverfront Villa in Nerul",
    location: "Nerul, North Goa",
    price: "₹ 11.50 Cr",
    image: "/images/villa-4.webp",
    bedrooms: 4,
    bathrooms: 4,
    area: "4200 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "riverfront-villa-nerul",
  },
  {
    id: "a7777777-7890-0123-ef01-23456789abcd",
    title: "Mediterranean Villa in Candolim",
    location: "Candolim, North Goa",
    price: "₹ 9.50 Cr",
    image: "/images/villa-1.webp",
    bedrooms: 3,
    bathrooms: 4,
    area: "3100 sq.ft.",
    listingType: "sale",
    verified: false,
    slug: "mediterranean-villa-candolim",
  },
  {
    id: "b8888888-8901-1234-f012-3456789abcde",
    title: "Panoramic Sea View Studio",
    location: "Dona Paula, Goa",
    price: "₹ 65,000 / mo",
    image: "/images/villa-2.webp",
    bedrooms: 1,
    bathrooms: 1,
    area: "750 sq.ft.",
    listingType: "rent",
    verified: true,
    slug: "panoramic-sea-view-studio-dona-paula",
  },
  {
    id: "c9999999-9012-2345-0123-456789abcdef",
    title: "Secluded Jungle Sanctuary",
    location: "Mandrem, North Goa",
    price: "₹ 1.80 L / mo",
    image: "/images/villa-3.webp",
    bedrooms: 3,
    bathrooms: 3,
    area: "2500 sq.ft.",
    listingType: "rent",
    verified: true,
    slug: "secluded-jungle-sanctuary-mandrem",
  },
  {
    id: "d0000000-0123-3456-1234-56789abcdef0",
    title: "Colonial Charm Villa in Saligao",
    location: "Saligao, North Goa",
    price: "₹ 6.80 Cr",
    image: "/images/villa-4.webp",
    bedrooms: 4,
    bathrooms: 4,
    area: "3300 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "colonial-charm-villa-saligao",
  },
  {
    id: "e1111111-1234-5678-2345-6789abcdef01",
    title: "Ultra Luxury Estate in Betul",
    location: "Betul, South Goa",
    price: "₹ 28.00 Cr",
    image: "/images/villa-1.webp",
    bedrooms: 6,
    bathrooms: 7,
    area: "8200 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "ultra-luxury-estate-betul",
  },
  {
    id: "f2222222-2345-6789-3456-789abcdef012",
    title: "Tropical Modern Villa in Guirim",
    location: "Guirim, North Goa",
    price: "₹ 5.90 Cr",
    image: "/images/villa-2.webp",
    bedrooms: 3,
    bathrooms: 3,
    area: "2900 sq.ft.",
    listingType: "sale",
    verified: false,
    slug: "tropical-modern-villa-guirim",
  },
  {
    id: "a3333333-3456-7890-4567-89abcdef0123",
    title: "Cozy Beachside Cottage",
    location: "Benaulim, South Goa",
    price: "₹ 95,000 / mo",
    image: "/images/villa-3.webp",
    bedrooms: 2,
    bathrooms: 2,
    area: "1200 sq.ft.",
    listingType: "rent",
    verified: true,
    slug: "cozy-beachside-cottage-benaulim",
  },
  {
    id: "b4444444-4567-8901-5678-9abcdef01234",
    title: "Hillside Oasis in Socorro",
    location: "Socorro, North Goa",
    price: "₹ 7.40 Cr",
    image: "/images/villa-4.webp",
    bedrooms: 4,
    bathrooms: 4,
    area: "3600 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "hillside-oasis-socorro",
  },
  {
    id: "c5555555-5678-9012-6789-abcdef012345",
    title: "Skyline View Penthouse",
    location: "Bambolim, Goa",
    price: "₹ 2.50 L / mo",
    image: "/images/villa-1.webp",
    bedrooms: 3,
    bathrooms: 4,
    area: "2700 sq.ft.",
    listingType: "rent",
    verified: true,
    slug: "skyline-view-penthouse-bambolim",
  },
  {
    id: "d6666666-6789-0123-789a-bcdef0123456",
    title: "Traditional Villa in Aldona",
    location: "Aldona, North Goa",
    price: "₹ 4.80 Cr",
    image: "/images/villa-2.webp",
    bedrooms: 3,
    bathrooms: 3,
    area: "2400 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "traditional-villa-aldona",
  },
  {
    id: "e7777777-7890-1234-89ab-cdef01234567",
    title: "Grand Portuguese Hacienda",
    location: "Raia, South Goa",
    price: "₹ 10.50 Cr",
    image: "/images/villa-3.webp",
    bedrooms: 5,
    bathrooms: 5,
    area: "5800 sq.ft.",
    listingType: "sale",
    verified: true,
    slug: "grand-portuguese-hacienda-raia",
  },
  {
    id: "f8888888-8901-2345-9abc-def012345678",
    title: "Boutique Garden Apartment",
    location: "Vagator, North Goa",
    price: "₹ 55,000 / mo",
    image: "/images/villa-4.webp",
    bedrooms: 1,
    bathrooms: 1,
    area: "850 sq.ft.",
    listingType: "rent",
    verified: false,
    slug: "boutique-garden-apartment-vagator",
  },
];

async function main() {
  console.log("🌱 Seeding database via pg (Sydney pooler)...");
  await client.connect();

  for (const p of mockProperties) {
    const query = `
      INSERT INTO "Property" ("id", "title", "location", "price", "image", "bedrooms", "bathrooms", "area", "listingType", "verified", "slug", "createdAt", "updatedAt")
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW())
      ON CONFLICT ("slug") DO UPDATE
      SET "title" = $2, "location" = $3, "price" = $4, "image" = $5, "bedrooms" = $6, "bathrooms" = $7, "area" = $8, "listingType" = $9, "verified" = $10, "updatedAt" = NOW()
    `;

    await client.query(query, [
      p.id,
      p.title,
      p.location,
      p.price,
      p.image,
      p.bedrooms,
      p.bathrooms,
      p.area,
      p.listingType,
      p.verified,
      p.slug
    ]);
  }

  console.log(`✅ Seeding complete. Successfully seeded ${mockProperties.length} properties.`);
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await client.end();
  });
